import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GoogleTagManager } from '@next/third-parties/google';
import Script from 'next/script';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <Script
        id="init-gtag"
        strategy="beforeInteractive"
        dangerouslySetInnerHTML={{
          __html: `
          console.log('beforeInteractive - new!');
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              
            gtag('consent', 'default', {
              'ad_storage': 'granted',
              'analytics_storage': 'granted',
              'ad_user_data': 'granted',
              'ad_personalization': 'granted'
              'functionality_storage': 'granted'
              'personalization_storage': 'granted'
              'security_storage': 'granted'
            });
            gtag('consent', 'update', {
              'ad_storage': 'granted',
              'analytics_storage': 'granted',
              'ad_user_data': 'granted',
              'ad_personalization': 'granted'
              'functionality_storage': 'granted'
              'personalization_storage': 'granted'
              'security_storage': 'granted'
            });
            
            console.log('done!');
          `,
        }}
    />
      <GoogleTagManager gtmId={process.env.GTM_ID as unknown as string} />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
